title: Amigas al Borde de un Ataque de Nervios
remote_theme: minima
baseurl: "/amigasalbordedeunataquedenervios"
collections:
  reparto:
    output: true
include:
  - assets/favicon.ico
  - assets/favicon.png
